project:
  type: website
  output-dir: docs
website:
  title: "My Website"
  favicon: /images/logo.png
  navbar:
    logo: /images/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: FYP Project.qmd
        text: FYP
      - href: Data Visualisation.qmd
        text: Data Visualisation
      - href: Wonton Mee Recipe.qmd
        text: Recipes
      - href: Reflection.qmd
        text: Reflection
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left


